# SPDX-FileCopyrightText: 2024 Hannes Bohring <hannes.bohring@ufz.de>
# SPDX-FileCopyrightText: 2024 Helmholtz Centre for Environmental Research (UFZ)
#
# SPDX-License-Identifier: AGPL-3.0-only
---

stages:
  - "build"

default:
  interruptible: true

.docker_login: &docker_login
  - 'echo "${CI_REGISTRY_PASSWORD}" | docker login --username "$CI_REGISTRY_USER" --password-stdin "${CI_REGISTRY}"'

.base_before_build_script:
  image: "docker:27-dind"
  services:
    - "docker:27-dind"

build-latest:
  stage: "build"
  extends: ".base_before_build_script"
  before_script:
    - *docker_login
  script:
    - "docker build -t ${CI_REGISTRY_IMAGE}:latest ."
    - "docker push --all-tags ${CI_REGISTRY_IMAGE}"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
    - when: "never"


build-release:
  stage: "build"
  extends: ".base_before_build_script"
  before_script:
    - *docker_login
  script:
    - "docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} ."
    - "docker push --all-tags ${CI_REGISTRY_IMAGE}"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+.\d+.\d+/'
      when: "always"
    - when: "never"


...
