# SPDX-FileCopyrightText: 2024 Helmholtz Centre for Environmental Research (UFZ)
#
# SPDX-License-Identifier: AGPL-3.0-only

version: '3'

services:

  web:
    image: "localhost/ecotoxfred"
    build: ./
    ports:
      - "8501:8501"  # Map container port 8501 to host port 8501
    user: ecotoxfred
    volumes:
      - "./.streamlit:/app/.streamlit"
