# SPDX-FileCopyrightText: 2023 Helmholtz Centre for Environmental Research (UFZ)
#
# SPDX-License-Identifier: AGPL-3.0-only

version: '3'

services:

  web:
    image: "localhost/streamlit:dev"
    build: ./
    ports:
      - "8501:8501"  # Map container port 8501 to host port 8501
    volumes:
      - "./src:/app"
      - "./src/config.yaml.sample:/secrets/config.yaml"
    env_file:
      - "secrets/.env"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL: "${OPENAI_MODEL}"
      NEO4J_URI: "${NEO4J_URI}"
      NEO4J_USERNAME: "${NEO4J_USERNAME}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD}"
