# SPDX-FileCopyrightText: 2024 Helmholtz Centre for Environmental Research (UFZ)
#
# SPDX-License-Identifier: AGPL-3.0-only

services:

  web:
    image: "ecotoxfred:dev"
    build: ./
    ports:
      - "8501:8501"
    user: ecotoxfred
    volumes:
      - "./.streamlit:/app/.streamlit"

  neo4j:
    image: triet20/neo4j-cheos
    container_name: neo4j-cheos
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./plugins:/plugins
    environment:
      NEO4J_AUTH: "neo4j/Phaewahjoh7IeS{ai4phaesh"
      NEO4J_PLUGINS: "[\"apoc\"]"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
