name: edt_env
channels:
  - conda-forge
dependencies:
  - python=3.10.*
  - langchain-openai
  - langchain
  - langchain-core
  - langchain-community
  - langgraph
  - langsmith
  - langchainhub
  - matplotlib
  - neo4j-python-driver
  - networkx
  - openai
  - pandas
  - pillow
  - plotly
  - pytest
  - pydantic
  - requests
  - streamlit
  - tenacity
  - toml
  - wikipedia
  - yaml
